[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "dark"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ffffff"
primaryColor = "#00ff5f"
font = "monospace"
